apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    uuid: 6ce17460-2163-4cff-a220-29f755929fff
  name: s-6ce17460-2163-4cff-a220-29f755929fff
  namespace: platform
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
    uuid: 6ce17460-2163-4cff-a220-29f755929fff
  type: ClusterIP
