apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    uuid: 33aae08f-b9c4-428b-903a-38bb9fd61539
  name: s-33aae08f-b9c4-428b-903a-38bb9fd61539
  namespace: platform
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
    uuid: 33aae08f-b9c4-428b-903a-38bb9fd61539
  type: ClusterIP
