apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
    uuid: 5346890e-23f0-4cd2-a49a-620ff63beace
  name: s-5346890e-23f0-4cd2-a49a-620ff63beace
  namespace: central
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: central
    uuid: 5346890e-23f0-4cd2-a49a-620ff63beace
  type: ClusterIP
