apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    uuid: 5a8b4456-b09d-421d-bd01-b969c348a77b
  name: s-5a8b4456-b09d-421d-bd01-b969c348a77b
  namespace: platform
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
    uuid: 5a8b4456-b09d-421d-bd01-b969c348a77b
  type: ClusterIP
