apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: f7bb70fd-b735-4a35-b1a0-175d5d96d17a
  name: t-f7bb70fd-b735-4a35-b1a0-175d5d96d17a
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: f7bb70fd-b735-4a35-b1a0-175d5d96d17a
  type: ClusterIP
