apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
    uuid: 97d4756d-559c-406e-b6c1-e1cfd1fbbb89
  name: 97d4756d-559c-406e-b6c1-e1cfd1fbbb89
  namespace: central
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: central
    uuid: 97d4756d-559c-406e-b6c1-e1cfd1fbbb89
  type: ClusterIP
