apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
  name: platforms-svc-headless
  namespace: platform
spec:
  clusterIP: None
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
  name: centrals-svc-headless
  namespace: central
spec:
  clusterIP: None
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: central
