apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
  name: platforms-svc
  namespace: platform
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
  name: centrals-svc
  namespace: central
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: central
  type: ClusterIP
