apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: ab541716-ae24-4a40-8ef5-6b6c63671e33
  name: t-ab541716-ae24-4a40-8ef5-6b6c63671e33
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: ab541716-ae24-4a40-8ef5-6b6c63671e33
  type: ClusterIP
