apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: cfadfa5c-29bc-4732-aa34-3cd4c19344c5
  name: t-cfadfa5c-29bc-4732-aa34-3cd4c19344c5
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: cfadfa5c-29bc-4732-aa34-3cd4c19344c5
  type: ClusterIP
