apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
    uuid: 6d0b47bf-5542-41b9-a4f0-7a601fbfd505
  name: s-6d0b47bf-5542-41b9-a4f0-7a601fbfd505
  namespace: central
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: central
    uuid: 6d0b47bf-5542-41b9-a4f0-7a601fbfd505
  type: ClusterIP
