apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: 8e570e1a-5c8c-47d9-b4f8-dda494474b30
  name: t-8e570e1a-5c8c-47d9-b4f8-dda494474b30
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: 8e570e1a-5c8c-47d9-b4f8-dda494474b30
  type: ClusterIP
