apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
  name: towers-svc-headless
  namespace: tower
spec:
  clusterIP: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
