apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
  name: towers-svc
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
  type: ClusterIP