apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
  name: t-cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: cd4f8ced-61cb-4afa-950b-b7ab5f0e36a4
  type: ClusterIP
