apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: 5c5cb218-c70c-4964-9adc-08a0072ca76e
  name: t-5c5cb218-c70c-4964-9adc-08a0072ca76e
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: 5c5cb218-c70c-4964-9adc-08a0072ca76e
  type: ClusterIP
