apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
    uuid: c2a3bbba-6480-4875-8872-bed486f836e1,
  name: s-c2a3bbba-6480-4875-8872-bed486f836e1,
  namespace: central
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: central
    uuid: c2a3bbba-6480-4875-8872-bed486f836e1,
  type: ClusterIP
