apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    uuid: fd2f64b5-baa7-4664-810b-a4f9786b005b
  name: s-fd2f64b5-baa7-4664-810b-a4f9786b005b
  namespace: platform
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
    uuid: fd2f64b5-baa7-4664-810b-a4f9786b005b
  type: ClusterIP
