apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: 445165c2-4186-4acc-b5e4-cf8d588a8a93
  name: t-445165c2-4186-4acc-b5e4-cf8d588a8a93
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: 445165c2-4186-4acc-b5e4-cf8d588a8a93
  type: ClusterIP
