apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    uuid: 063e6790-c617-4193-8242-c8b59c3c2b27
  name: s-063e6790-c617-4193-8242-c8b59c3c2b27
  namespace: platform
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
    uuid: 063e6790-c617-4193-8242-c8b59c3c2b27
  type: ClusterIP
