apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    uuid: f64060b0-42db-4bfd-a514-eb77f27ef227
  name: s-f64060b0-42db-4bfd-a514-eb77f27ef227
  namespace: platform
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: platform
    uuid: f64060b0-42db-4bfd-a514-eb77f27ef227
  type: ClusterIP
