apiVersion: v1
kind: Service
metadata:
  labels:
    app: tower
    uuid: 369cd047-284a-4bb8-8804-68f4c83f1942
  name: t-369cd047-284a-4bb8-8804-68f4c83f1942
  namespace: tower
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: tower
    uuid: 369cd047-284a-4bb8-8804-68f4c83f1942
  type: ClusterIP
