apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
    uuid: 872b12d7-f9ef-4b2e-84d6-09be2634d7ee
  name: s-872b12d7-f9ef-4b2e-84d6-09be2634d7ee
  namespace: central
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: central
    uuid: 872b12d7-f9ef-4b2e-84d6-09be2634d7ee
  type: ClusterIP
